### ISSUE TITLE
Quotes are stripped from did tasks.

### ISSUE THREAD

**Issue by drewlustro** [chrisallenlane/node-did#2]
Example:

```bash
# Add a new one with quotes
did Posted new blog "How to ever so slightly break node-did" today.

# Replay log lacks quotes
did log
1  Posted new blog How to ever so slightly break node-did today.  10 Jan | 06:07 PM
```

**Comment by chrisallenlane** [comment]
Huh - weird. Confirmed.

Thanks for the bug report. I'll take a look at this in the next day or two.

**Comment by chrisallenlane** [comment]
Actually, I just had a few minutes to look at this.

Bad news: I can't/won't fix it.
Good news: it's easily worked around.

A little poking revealed that the quotation marks had already been stripped by the time that `docopt` (the option parser) had handed the options to me. That means that there's nothing that I can (easily) do to solve this problem.

And that makes sense if you think about it. `docopt` has been configured to accept an array of strings, so this:

```sh
did foo bar baz
```

Is really just a shorthand for this:

```sh
did "foo" "bar" "baz"
```

In other words - it's not that your quotations are being stripped from inside a string. Rather, you're inputting an _array_ of strings, some of which are explicitly quoted, and some not.

The good news: this is trivially worked around by wrapping your entire log entry in single quotes:

```sh
did log 'Posted new blog "How to ever so slightly break node-did" today.'
```

You will then get the expected output.

If it's more convenient, you can also export `EDITOR` and write log entries that contain quotations (and other shell metacharacters) directly in `vim` or whatever.

Does that make sense? I hope that helps!

**Comment by drewlustro** [comment]
Hah! I, too, I realize now that the quotes are stripped on the shell level. 

Thanks!
