### ISSUE TITLE
Can the sqlite database be transferred?

### ISSUE THREAD

**Issue by chadmando** [chrisallenlane/node-did#3]
First off, thank you for a great tool. I was trying to move my database from macOS to a Windows installation. I was having trouble finding the db location in Windows.  Any thoughts all which files and their respective locations that would need to be copied to make this happen?   Or if it is even feasible.

**Comment by chrisallenlane** [comment]
> First off, thank you for a great tool. 

My pleasure. Glad you're enjoying it!

> Or if it is even feasible.

It's definitely feasible. `did` keeps all of its log data in a file whose path defaults to `~/.did.sqlite3` on Unix-like systems. If you copy that file to the "appropriate location" on Windows, you should be good-to-go.

Now, regarding that "appropriate location": honestly, I haven't meaningfully used Windows in like 10 years, so I'm not sure. This Stack Exchange thread may put you on the right track, though:

https://stackoverflow.com/questions/9228950/what-is-the-alternative-for-users-home-directory-on-windows-command-prompt

So, it looks like you should have a folder in your `Documents and Settings` directory, I guess? If you can find that, try putting your `.did.sqlite3` file in there, and let's see what we get :)

**Comment by chadmando** [comment]
@chrisallenlane Got it.  Just copy the .did.sqlite3 file from the ~/ directory into the c:\Users\[username]\ (for Win7) and its transferred.  Thanks for your help, especially the LMGTFY on the windows ~/ equivalent.
